version: '3'

services:

    reverse-proxy:
        image: nginx:1.17.10
        container_name: reverse_proxy_test
        depends_on: 
            - cat-app
            - cat2-app
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
    
    cat-app:
        image: cat-app
        container_name: cat-app
        build:
            context: ./cat-app
        ports:
            - 8080:5000
        restart: on-failure
    
    cat2-app:
        image: cat2-app
        container_name: cat2-app
        build:
            context: ./cat2-app
        ports:
            - 8888:5000
        restart: on-failure

